const express = require("express");
const pool = require("../db");
const { getSession } = require("../sessions");
const { buildInsights } = require("../services/supportInsights");
const router = express.Router();
let schemaPromise;
const TABLES = { systems: "support_systems", categories: "support_categories", issues: "support_issues", resolutions: "support_resolutions", causes: "support_causes" };

async function schema() {
  if (schemaPromise) return schemaPromise;
  schemaPromise = (async () => {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS support_systems (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE TABLE IF NOT EXISTS support_categories (id BIGSERIAL PRIMARY KEY, system_id BIGINT NOT NULL REFERENCES support_systems(id), name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(system_id,name));
      CREATE TABLE IF NOT EXISTS support_issues (id BIGSERIAL PRIMARY KEY, category_id BIGINT NOT NULL REFERENCES support_categories(id), name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(category_id,name));
      CREATE TABLE IF NOT EXISTS support_resolutions (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE TABLE IF NOT EXISTS support_causes (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE TABLE IF NOT EXISTS support_requests (id BIGSERIAL PRIMARY KEY, support_date DATE NOT NULL DEFAULT CURRENT_DATE, start_at TIMESTAMPTZ NOT NULL, end_at TIMESTAMPTZ NOT NULL, elapsed_seconds INTEGER NOT NULL CHECK(elapsed_seconds >= 0), user_id INTEGER NOT NULL REFERENCES users(id), location_id INTEGER NOT NULL REFERENCES locations(id), system_id BIGINT NOT NULL REFERENCES support_systems(id), category_id BIGINT NOT NULL REFERENCES support_categories(id), issue_id BIGINT NOT NULL REFERENCES support_issues(id), error_type TEXT NOT NULL CHECK(error_type IN ('user','system','other')), resolution_id BIGINT NOT NULL REFERENCES support_resolutions(id), cause_id BIGINT NOT NULL REFERENCES support_causes(id), description TEXT, resolution_notes TEXT, reference_number TEXT, created_by INTEGER NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS idx_support_requests_date ON support_requests(support_date);
      CREATE INDEX IF NOT EXISTS idx_support_requests_dimensions ON support_requests(location_id,user_id,system_id,category_id,issue_id,error_type);
    `);
    await pool.query(`INSERT INTO support_systems(name,sort_order) SELECT x.name,x.ord FROM unnest($1::text[]) WITH ORDINALITY x(name,ord) ON CONFLICT(name) DO NOTHING`, [["NetSuite","EPOS","WooCommerce","Hardware","Network","Microsoft 365","Printing","Other"]]);
    await pool.query(`INSERT INTO support_causes(name,sort_order) SELECT x.name,x.ord FROM unnest($1::text[]) WITH ORDINALITY x(name,ord) ON CONFLICT(name) DO NOTHING`, [["User Knowledge","Process Not Followed","Process Gap","System Fault","Configuration","Data Issue","Permissions","Hardware","Network","External Service","Unknown"]]);
    await pool.query(`INSERT INTO support_resolutions(name,sort_order) SELECT x.name,x.ord FROM unnest($1::text[]) WITH ORDINALITY x(name,ord) ON CONFLICT(name) DO NOTHING`, [["Guidance Provided","Training Provided","Data Corrected","Configuration Changed","Permissions Changed","System Fixed","Workaround Provided","Escalated","No Fault Found","Further Investigation Required"]]);
  })().catch(e => { schemaPromise = null; throw e; });
  return schemaPromise;
}
async function auth(req,res,next) { const token=(req.headers.authorization||"").replace(/^Bearer /,""); const s=token&&await getSession(token); if(!s)return res.status(401).json({ok:false,error:"Not authenticated"}); req.supportUserId=Number(s.id||s.user_id); req.supportRole=String(s.activeRole?.name||""); next(); }
function admin(req) { return /admin|director|manager/i.test(req.supportRole); }
function range(q) { return [q.from || new Date(Date.now()-29*86400000).toISOString().slice(0,10), q.to || new Date().toISOString().slice(0,10)]; }
router.use(auth); router.use(async(req,res,next)=>{try{await schema();next();}catch(e){next(e);}});
router.get("/bootstrap", async(req,res)=>{ const [config,users,locations]=await Promise.all([pool.query(`SELECT 'systems' type,id,name,active,sort_order,NULL::bigint parent_id FROM support_systems UNION ALL SELECT 'categories',id,name,active,sort_order,system_id FROM support_categories UNION ALL SELECT 'issues',id,name,active,sort_order,category_id FROM support_issues UNION ALL SELECT 'resolutions',id,name,active,sort_order,NULL FROM support_resolutions UNION ALL SELECT 'causes',id,name,active,sort_order,NULL FROM support_causes ORDER BY type,sort_order,name`),pool.query(`SELECT u.id,trim(concat(u.firstname,' ',u.lastname)) name,u.location_id,l.name location_name FROM users u LEFT JOIN locations l ON l.id=u.location_id ORDER BY u.lastname,u.firstname`),pool.query(`SELECT id,name FROM locations ORDER BY name`)]);res.json({ok:true,canConfigure:admin(req),currentUserId:req.supportUserId,config:config.rows,users:users.rows,locations:locations.rows});});
router.post("/issues/quick-add",async(req,res)=>{const name=String(req.body?.name||"").trim(),categoryId=Number(req.body?.categoryId),systemId=Number(req.body?.systemId);if(name.length<3)return res.status(400).json({ok:false,error:"Issue names must contain at least 3 characters."});const relationship=await pool.query(`SELECT 1 FROM support_categories WHERE id=$1 AND system_id=$2 AND active=TRUE`,[categoryId,systemId]);if(!relationship.rowCount)return res.status(400).json({ok:false,error:"Select a valid active System and Category first."});const existing=await pool.query(`SELECT id,name,active,sort_order,category_id parent_id,'issues' type FROM support_issues WHERE category_id=$1 AND lower(name)=lower($2) LIMIT 1`,[categoryId,name]);if(existing.rowCount){if(!existing.rows[0].active)await pool.query(`UPDATE support_issues SET active=TRUE,updated_at=NOW() WHERE id=$1`,[existing.rows[0].id]);return res.json({ok:true,item:{...existing.rows[0],active:true},existing:true})}const created=await pool.query(`INSERT INTO support_issues(category_id,name) VALUES($1,$2) RETURNING id,name,active,sort_order,category_id parent_id,'issues' type`,[categoryId,name]);res.status(201).json({ok:true,item:created.rows[0]});});
router.post("/requests", async(req,res)=>{const b=req.body||{},required={userId:"User",locationId:"Location",systemId:"System",categoryId:"Category",issueId:"Issue",errorType:"Error Type",resolutionId:"Resolution",causeId:"Cause",startAt:"Start time",endAt:"End time"},missing=Object.entries(required).filter(([key])=>!b[key]).map(([,label])=>label);if(missing.length)return res.status(400).json({ok:false,error:`Please complete: ${missing.join(", ")}.`});const start=new Date(b.startAt),end=new Date(b.endAt);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<start)return res.status(400).json({ok:false,error:"Enter a valid start and end time; end time must be after start time."});const elapsed=Math.max(0,Math.round((end-start)/1000)); const valid=await pool.query(`SELECT 1 FROM support_categories c JOIN support_issues i ON i.category_id=c.id WHERE c.id=$1 AND c.system_id=$2 AND i.id=$3`,[b.categoryId,b.systemId,b.issueId]); if(!valid.rowCount)return res.status(400).json({ok:false,error:"Invalid System, Category and Issue combination."}); const r=await pool.query(`INSERT INTO support_requests(support_date,start_at,end_at,elapsed_seconds,user_id,location_id,system_id,category_id,issue_id,error_type,resolution_id,cause_id,description,resolution_notes,reference_number,created_by) VALUES(COALESCE($1::date,$2::timestamptz::date),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING id`,[b.supportDate||null,b.startAt,b.endAt,elapsed,b.userId,b.locationId,b.systemId,b.categoryId,b.issueId,b.errorType,b.resolutionId,b.causeId,b.description||null,b.resolutionNotes||null,b.referenceNumber||null,req.supportUserId]);res.status(201).json({ok:true,id:r.rows[0].id,elapsedSeconds:elapsed});});
router.get("/requests", async(req,res)=>{const [from,to]=range(req.query),p=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(10,Number(req.query.limit)||25)),vals=[from,to],where=[`r.support_date BETWEEN $1 AND $2`]; for(const [key,col] of [["locationId","r.location_id"],["userId","r.user_id"],["systemId","r.system_id"],["categoryId","r.category_id"],["issueId","r.issue_id"],["errorType","r.error_type"]])if(req.query[key]){vals.push(req.query[key]);where.push(`${col}=$${vals.length}`)} if(req.query.search){vals.push(`%${req.query.search}%`);where.push(`concat_ws(' ',u.firstname,u.lastname,l.name,s.name,c.name,i.name,r.description,r.reference_number) ILIKE $${vals.length}`)} const base=`FROM support_requests r JOIN users u ON u.id=r.user_id JOIN locations l ON l.id=r.location_id JOIN support_systems s ON s.id=r.system_id JOIN support_categories c ON c.id=r.category_id JOIN support_issues i ON i.id=r.issue_id JOIN support_resolutions rr ON rr.id=r.resolution_id JOIN support_causes ca ON ca.id=r.cause_id WHERE ${where.join(" AND ")}`; const count=await pool.query(`SELECT count(*) ${base}`,vals); vals.push(limit,(p-1)*limit);const rows=await pool.query(`SELECT r.*,trim(concat(u.firstname,' ',u.lastname)) user_name,l.name location_name,s.name system_name,c.name category_name,i.name issue_name,rr.name resolution_name,ca.name cause_name ${base} ORDER BY r.support_date DESC,r.start_at DESC LIMIT $${vals.length-1} OFFSET $${vals.length}`,vals);res.json({ok:true,rows:rows.rows,total:Number(count.rows[0].count),page:p,limit});});
router.get("/analytics", async(req,res)=>{const [from,to]=range(req.query), vals=[from,to],where=[`r.support_date BETWEEN $1 AND $2`];for(const [key,col] of [["locationId","r.location_id"],["userId","r.user_id"],["systemId","r.system_id"],["categoryId","r.category_id"],["issueId","r.issue_id"],["errorType","r.error_type"]])if(req.query[key]){vals.push(req.query[key]);where.push(`${col}=$${vals.length}`)} const w=where.join(" AND "); const [kpis,breakdowns,trends,groups]=await Promise.all([pool.query(`SELECT count(*) requests,coalesce(sum(elapsed_seconds),0) seconds,coalesce(avg(elapsed_seconds),0) average_seconds,count(*) FILTER(WHERE error_type='user') user_errors,count(*) FILTER(WHERE error_type='system') system_errors,count(DISTINCT location_id) locations FROM support_requests r WHERE ${w}`,vals),pool.query(`SELECT dimension,name,requests,seconds FROM (SELECT 'Location' dimension,l.name,count(*) requests,sum(r.elapsed_seconds) seconds FROM support_requests r JOIN locations l ON l.id=r.location_id WHERE ${w} GROUP BY l.name UNION ALL SELECT 'System',s.name,count(*),sum(r.elapsed_seconds) FROM support_requests r JOIN support_systems s ON s.id=r.system_id WHERE ${w} GROUP BY s.name UNION ALL SELECT 'Issue',i.name,count(*),sum(r.elapsed_seconds) FROM support_requests r JOIN support_issues i ON i.id=r.issue_id WHERE ${w} GROUP BY i.name UNION ALL SELECT 'Cause',c.name,count(*),sum(r.elapsed_seconds) FROM support_requests r JOIN support_causes c ON c.id=r.cause_id WHERE ${w} GROUP BY c.name) x ORDER BY dimension,requests DESC`,vals),pool.query(`SELECT support_date date,count(*) requests,sum(elapsed_seconds) seconds FROM support_requests r WHERE ${w} GROUP BY support_date ORDER BY support_date`,vals),pool.query(`SELECT s.name system_name,c.name category_name,i.name issue_name,count(*) requests,count(*) FILTER(WHERE error_type='user') user_errors,count(*) FILTER(WHERE error_type='system') system_errors,count(DISTINCT user_id) users,count(DISTINCT location_id) locations,sum(elapsed_seconds) seconds FROM support_requests r JOIN support_systems s ON s.id=r.system_id JOIN support_categories c ON c.id=r.category_id JOIN support_issues i ON i.id=r.issue_id WHERE ${w} GROUP BY s.name,c.name,i.name`,vals)]); const k=kpis.rows[0];res.json({ok:true,kpis:{...k,userErrorPercent:Number(k.requests)?Number(k.user_errors)*100/Number(k.requests):0,systemErrorPercent:Number(k.requests)?Number(k.system_errors)*100/Number(k.requests):0,recurringIssues:groups.rows.filter(g=>Number(g.requests)>=4).length},breakdowns:breakdowns.rows,trends:trends.rows,insights:buildInsights(groups.rows)});});
router.post("/config/:type",async(req,res)=>{if(!admin(req))return res.status(403).json({ok:false,error:"Configuration requires a manager or admin role."});const table=TABLES[req.params.type];if(!table)return res.status(404).end();const parent=req.params.type==='categories'?'system_id':req.params.type==='issues'?'category_id':null;const cols=parent?'name,active,sort_order,'+parent:'name,active,sort_order';const values=parent?[req.body.name,req.body.active!==false,Number(req.body.sortOrder)||0,req.body.parentId]:[req.body.name,req.body.active!==false,Number(req.body.sortOrder)||0];const placeholders=values.map((_,i)=>`$${i+1}`).join(',');const r=await pool.query(`INSERT INTO ${table}(${cols}) VALUES(${placeholders}) RETURNING *`,values);res.status(201).json({ok:true,item:r.rows[0]});});
router.put("/config/:type/:id",async(req,res)=>{if(!admin(req))return res.status(403).json({ok:false,error:"Configuration requires a manager or admin role."});const table=TABLES[req.params.type];if(!table)return res.status(404).end();const parent=req.params.type==='categories'?'system_id':req.params.type==='issues'?'category_id':null;const vals=[req.body.name,req.body.active!==false,Number(req.body.sortOrder)||0];let set=`name=$1,active=$2,sort_order=$3,updated_at=NOW()`;if(parent){vals.push(req.body.parentId);set+=`,${parent}=$4`}vals.push(req.params.id);const r=await pool.query(`UPDATE ${table} SET ${set} WHERE id=$${vals.length} RETURNING *`,vals);res.json({ok:true,item:r.rows[0]});});
router.delete("/config/:type/:id",async(req,res)=>{if(!admin(req))return res.status(403).json({ok:false,error:"Configuration requires a manager or admin role."});const type=req.params.type,table=TABLES[type],id=Number(req.params.id);if(!table)return res.status(404).json({ok:false,error:"Unknown configuration type."});if(!Number.isInteger(id)||id<1)return res.status(400).json({ok:false,error:"Invalid configuration ID."});const references={systems:[["support_categories","system_id","categories"],["support_requests","system_id","support requests"]],categories:[["support_issues","category_id","issues"],["support_requests","category_id","support requests"]],issues:[["support_requests","issue_id","support requests"]],resolutions:[["support_requests","resolution_id","support requests"]],causes:[["support_requests","cause_id","support requests"]]}[type]||[];for(const [refTable,column,label] of references){const used=await pool.query(`SELECT count(*)::int count FROM ${refTable} WHERE ${column}=$1`,[id]);if(used.rows[0].count>0)return res.status(409).json({ok:false,error:`This value cannot be deleted because it is used by ${used.rows[0].count} ${label}.`})}const deleted=await pool.query(`DELETE FROM ${table} WHERE id=$1 RETURNING id,name`,[id]);if(!deleted.rowCount)return res.status(404).json({ok:false,error:"Configuration value not found."});res.json({ok:true,item:deleted.rows[0]});});
router.use((err,req,res,next)=>{console.error("Support tracker:",err);res.status(500).json({ok:false,error:"Support Tracker request failed."});});
module.exports=router;
